### ISSUE TITLE
I just changed

### ISSUE THREAD

**Issue by limelect** [WouterVanNifterick/C-To-Delphi#2]
I changed on Delphi hello(i) to hello(i+.. errors
and to i+1 errors

**Comment by WouterVanNifterick** [comment]
While you type, you should see errors in the bottom panel, because halfway the converter encounters invalid code.
The example code is simple enough that the built in DWS compiler can even run the resulting pascal code once you're done typing.

![image](https://user-images.githubusercontent.com/5777405/32810484-6759995c-c99b-11e7-9efc-7967afe08a7b.png)
